# Generated by Django 5.2.6 on 2026-09-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to='academics.facultyprofile')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignment', to='academics.section')),
            ],
        ),
    ]
